
["Geode Generation Configs"]
	#Average Chunks per Tier 1 Geode
	#Range: > 1
	"Chunks Per Tier 1 Geodes" = 16
	#Average Chunks per Tier 2 Geode
	#Range: > 1
	"Chunks Per Tier 2 Geodes" = 32
	#Average Chunks per Tier 3 Geode
	#Range: > 1
	"Chunks Per Tier 3 Geodes" = 64
	#Tier 1 Geode Minimum Y Level
	#Range: -64 ~ 320
	"Tier 1 Geode Minimum Y" = 0
	#Tier 1 Geode Maximum Y Level
	#Range: -64 ~ 320
	"Tier 1 Geode Maximum Y" = 128
	#Tier 2 Geode Minimum Y Level
	#Range: -64 ~ 320
	"Tier 2 Geode Minimum Y" = -32
	#Tier 2 Geode Maximum Y Level
	#Range: -64 ~ 320
	"Tier 2 Geode Maximum Y" = 32
	#Tier 3 Geode Minimum Y Level
	#Range: -64 ~ 320
	"Tier 3 Geode Minimum Y" = -64
	#Tier 3 Geode Maximum Y Level
	#Range: -64 ~ 320
	"Tier 3 Geode Maximum Y" = 0

["Cluster Growth Configs"]
	#Base Cluster Growth Rate (ticks per growth attempt)
	#Range: > 1
	"Base Cluster Growth Rate" = 5
	#Cluster Growth Rate per Tier (ticks per growth attempt)
	#Range: > 1
	"Tier Cluster Growth Rate" = 5

[Debug]
	#Log Debug Messages?
	"Debug Messages" = false

